### ISSUE TITLE
When I running Demo #1 err happens

### ISSUE THREAD

**Issue by jed057** [SynFutures/oyster-sdk#45]
TypeError: Cannot read properties of undefined (reading 'gate')
    at SynFuturesV3.<anonymous> (D:\syn\node_modules\@synfutures\oyster-sdk\build\synfuturesV3Core.js:307:58)
    at Generator.next (<anonymous>)
    at D:\syn\node_modules\@synfutures\oyster-sdk\build\synfuturesV3Core.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\syn\node_modules\@synfutures\oyster-sdk\build\synfuturesV3Core.js:4:12)
    at SynFuturesV3.getAllInstruments (D:\syn\node_modules\@synfutures\oyster-sdk\build\synfuturesV3Core.js:306:16)
    at d:\syn\src\demo.ts:7:35
    at Generator.next (<anonymous>)
    at d:\syn\build\demo.js:8:71
    at new Promise (<anonymous>) {stack: 'TypeError: Cannot read properties of undefine…demo.js:8:71
    at new Promise (<anonymous>)', message: "Cannot read properties of undefined (reading 'gate')"}

Pls let me know what should i do. thx

**Comment by jed057** [comment]
Forget about it, have solved it
