### ISSUE TITLE
An error occurred: TypeError: Cannot read properties of undefined (reading 'gate')

### ISSUE THREAD

**Issue by itsHaseebSaeed** [SynFutures/oyster-sdk#62]
An error occurred: TypeError: Cannot read properties of undefined (reading 'gate')
    at SynFuturesV3.<anonymous> (/Users/haseebsaeed/codes/synfutures-js-demo/node_modules/@synfutures/oyster-sdk/build/synfuturesV3Core.js:307:58)
    at Generator.next (<anonymous>)
    at /Users/haseebsaeed/codes/synfutures-js-demo/node_modules/@synfutures/oyster-sdk/build/synfuturesV3Core.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/haseebsaeed/codes/synfutures-js-demo/node_modules/@synfutures/oyster-sdk/build/synfuturesV3Core.js:4:12)
    at SynFuturesV3.getAllInstruments (/Users/haseebsaeed/codes/synfutures-js-demo/node_modules/@synfutures/oyster-sdk/build/synfuturesV3Core.js:306:16)
    at main (/Users/haseebsaeed/codes/synfutures-js-demo/demo.js:10:35)
    at Object.<anonymous> (/Users/haseebsaeed/codes/synfutures-js-demo/demo.js:42:1)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)

**Comment by itsHaseebSaeed** [comment]
So it happens when you miss the part to add blast_rpc in the .env file.
